apiVersion: v1
kind: Service
metadata:
  name: legallovestech-frontend
  namespace: legallovestech
  labels:
    app: legallovestech
spec:
  type: ClusterIP
  selector:
    app: legallovestech
  ports:
    - name: http
      port: 80
      targetPort: http
